name: Terraform Deploy

on: 
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 3-tier-app-eks/infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::431445718171:role/serverlessinfra
          aws-region: us-east-2
          audience: sts.amazonaws.com

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      # 1. Native Format Check
      - name: Terraform Format
        run: terraform fmt -recursive

      # 2. Native Validation
      - name: Terraform Init & Validate
        run: |
          terraform init 
          terraform validate

      # 3. TFLint (Linter)
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: "v0.52.0"
          

      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact --force # this give out exit code 0 to by pass the fail

      - name: Terraform apply
        run: terraform apply -auto-approve
      
